import glob
import os
import subprocess


def _get_parent_dir(path: str) -> str:
    return os.path.split(path)[0]


def _get_file_name_without_ext(path: str) -> str:
    return os.path.split(path)[1].split('.')[0]


def compile_ui() -> None:
    curdir = _get_parent_dir(os.path.realpath(__file__))
    uidir = os.path.join(_get_parent_dir(curdir), "ui")
    uis = []
    with open(os.path.join(uidir, "__init__.py"), mode="w+") as initf:
        initf.write("# Generated by UI compiler\n\n")
        for src in glob.glob(os.path.join(curdir, "*.ui")):
            name = _get_file_name_without_ext(src)
            out = os.path.join(uidir, f"_ui_{name}.py")
            print("Compiling", name, "...")
            subprocess.check_call(
                ["python", "-m", "PyQt5.uic.pyuic", src, "-o", out])
            initf.write(f"from ._ui_{name} import Ui_{name} as {name}\n")
            uis.append(name)
        print("Generating UI module...")
        initf.write("\n\n__all__ = (\n")
        for name in uis:
            initf.write(f"    \"{name}\",\n")
        initf.write(")\n")
