name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macOS-latest']
        python-version: ['3.7', '3.8']
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.python-version }} ${{ matrix.os }} 
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip || exit $LASTEXITCODE
        pwsh -c ./tools.ps1 dep || exit $LASTEXITCODE
        pwsh -c ./tools.ps1 dep-dev || exit $LASTEXITCODE
    - name: Compile UI
      run: pwsh -c ./tools.ps1 gen-ui
    - name: Lint
      run: pwsh -c ./tools.ps1 lint
    - name: Test
      if: matrix.os != 'ubuntu-latest'
      run: pwsh -c ./tools.ps1 testcov
    - name: Test without UI
      if: matrix.os == 'ubuntu-latest'
      run: pwsh -c ./tools.ps1 testcov-noui
    - name: Upload reports
      uses: actions/upload-artifact@v1
      with:
        name: test-${{ matrix.os }}-${{ matrix.python-version }}
        path: ./htmlcov
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip || exit $LASTEXITCODE
        pwsh -c ./tools.ps1 dep || exit $LASTEXITCODE
        pwsh -c ./tools.ps1 dep-dev || exit $LASTEXITCODE
    - name: Compile UI
      run: pwsh -c ./tools.ps1 gen-ui
    - name: Build package
      run: |
        python -m build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist